### ISSUE TITLE
Bios Settings

### ISSUE THREAD

**Issue by telesth** [asoji/hackintosh-rog-strix-b550f#1]
Hey @asoji, could you please share with us your BIOS configs? What's changed like fastboot, SCM? I'm using the latest BIOS version and all the tutorials I found on the internet use a different BIOS version and options.

**Comment by asoji** [comment]
I just personally follow everything recommended [here](https://dortania.github.io/OpenCore-Install-Guide/AMD/zen.html#amd-bios-settings), those work for me perfectly.

**Comment by telesth** [comment]
@asoji I have the very same motherboard, followed the same guide and I can't boot at all

**Comment by asoji** [comment]
I assume also a ASUS ROG Strix B550-F Gaming Wi-Fi board?

**Comment by asoji** [comment]
ignore what i just said, I'll take a look at my BIOS later

what BIOS version?

**Comment by telesth** [comment]
> ignore what i just said, I'll take a look at my BIOS later
> 
> what BIOS version?

@asoji I'm using the latest version 3404.

**Comment by telesth** [comment]
@asoji I've downgraded my bios to your same version and no lucky... I'm always stuck on that:

51:752 00:013 OCAK: [OK] SMBIOS Patch success
51:766 00:014 OCAK: Failed to pk find com.apple.driver.AppleIntelCPUPowerManagement - Not Found
51:781 00:014 OCAK: [OK] Skipping dummy AppleIntelCPUPowerManagement patch on 230300
51:794 00:013 OCAK: Registering 0 APFS timeout
51:808 00:013 OCAK: Patching invalid size 1ADFF0 with ED1000 for com.apple.filesystems.apfs
51:822 00:013 OCAK: [OK] Patch success ApfsDisableTrim
51:835 00:013 OCAK: 64-bit CaseySJ | probeBusGated | Disable 10 bit tags | 12.0+ replace count - 1
51:877 00:041 OC: Prelinked patcher result 16 for com.apple.iokit.IOPCIFamily (CaseySJ | probeBusGated | Disable 10 bit tags | 12.0+) - Success
51:930 00:053 OC: Prelinked status - Success
51:950 00:020 AAPL: #[EB.LD.LKFS|-?] Ok(0)
51:963 00:013 AAPL: #[EB.LD.LKC|-?] Ok(0)
51:979 00:015 AAPL: #[EB|BST:REV1]
51:992 00:013 AAPL: #[EB|CSR:OUT] 0x00000040
52:007 00:014 AAPL: #[EB.BST.FBS|+]
52:021 00:013 AAPL: #[EB.BST.FBS|ADSZ] 0
52:034 00:013 AAPL: #[EB.BST.FBS|KSSZ] 0
52:047 00:013 AAPL: #[EB|SB:SBGMFNS] x86legacyap.im4m
52:060 00:013 AAPL: #[EB|RH:PF] usr\standalone\OS.dmg.root_hash
52:118 00:058 AAPL: #[EB|RH:MF] <"usr\\standalone\\OS.dmg.root_hash.x86legacyap.im4m">
52:132 00:013 AAPL: #[EB.LD.LF|IN] 0 1 <"usr\\standalone\\OS.dmg.root_hash"> <"0">
52:148 00:016 AAPL: #[EB.LD.OFS|OPEN!] Err(0xE) <"usr\\standalone\\OS.dmg.root_hash">
52:161 00:013 AAPL: #[EB.RH.LRH|P!] Err(0xE) <- EB.LD.LF
52:174 00:013 AAPL: #[EB.BST.FBS|!] Err(0xE) <- EB.RH.LRH
52:188 00:013 OCSMC: SmcReadValue Key 4D535463 Size 1
52:201 00:013 OCSMC: SmcReadValue Key 4D534163 Size 2
52:214 00:013 AAPL: #[EB|LOG:DT] 2024-02-14T03:34:59
52:227 00:013 AAPL: #[EB|LOG:EXITBS:START] 2024-02-14T03:34:59

**Comment by asoji** [comment]
Those seem like errors from OpenCore itself..

Quite honestly I have no idea as I had friends help me out with my OC

**Comment by dynamyc010** [comment]
> @asoji I've downgraded my bios to your same version and no lucky... I'm always stuck on that:
> 
> 51:752 00:013 OCAK: [OK] SMBIOS Patch success 51:766 00:014 OCAK: Failed to pk find com.apple.driver.AppleIntelCPUPowerManagement - Not Found 51:781 00:014 OCAK: [OK] Skipping dummy AppleIntelCPUPowerManagement patch on 230300 51:794 00:013 OCAK: Registering 0 APFS timeout 51:808 00:013 OCAK: Patching invalid size 1ADFF0 with ED1000 for com.apple.filesystems.apfs 51:822 00:013 OCAK: [OK] Patch success ApfsDisableTrim 51:835 00:013 OCAK: 64-bit CaseySJ | probeBusGated | Disable 10 bit tags | 12.0+ replace count - 1 51:877 00:041 OC: Prelinked patcher result 16 for com.apple.iokit.IOPCIFamily (CaseySJ | probeBusGated | Disable 10 bit tags | 12.0+) - Success 51:930 00:053 OC: Prelinked status - Success 51:950 00:020 AAPL: #[EB.LD.LKFS|-?] Ok(0) 51:963 00:013 AAPL: #[EB.LD.LKC|-?] Ok(0) 51:979 00:015 AAPL: #[EB|BST:REV1] 51:992 00:013 AAPL: #[EB|CSR:OUT] 0x00000040 52:007 00:014 AAPL: #[EB.BST.FBS|+] 52:021 00:013 AAPL: #[EB.BST.FBS|ADSZ] 0 52:034 00:013 AAPL: #[EB.BST.FBS|KSSZ] 0 52:047 00:013 AAPL: #[EB|SB:SBGMFNS] x86legacyap.im4m 52:060 00:013 AAPL: #[EB|RH:PF] usr\standalone\OS.dmg.root_hash 52:118 00:058 AAPL: #[EB|RH:MF] <"usr\standalone\OS.dmg.root_hash.x86legacyap.im4m"> 52:132 00:013 AAPL: #[EB.LD.LF|IN] 0 1 <"usr\standalone\OS.dmg.root_hash"> <"0"> 52:148 00:016 AAPL: #[EB.LD.OFS|OPEN!] Err(0xE) <"usr\standalone\OS.dmg.root_hash"> 52:161 00:013 AAPL: #[EB.RH.LRH|P!] Err(0xE) <- EB.LD.LF 52:174 00:013 AAPL: #[EB.BST.FBS|!] Err(0xE) <- EB.RH.LRH 52:188 00:013 OCSMC: SmcReadValue Key 4D535463 Size 1 52:201 00:013 OCSMC: SmcReadValue Key 4D534163 Size 2 52:214 00:013 AAPL: #[EB|LOG:DT] 2024-02-14T03:34:59 52:227 00:013 AAPL: #[EB|LOG:EXITBS:START] 2024-02-14T03:34:59

If you're sure your config doesn't have any flaws in it, you could try a different USB to boot off of. Some USBs are finnicky with OC, and may be worth attempting.

Otherwise just upload your config somewhere and I'll take a lookie at it. Preferably include at least a list of your kexts as a screenshot or something along those lines.
