### ISSUE TITLE
MSI Radeon RX 570 Armor 8GB ? 

### ISSUE THREAD

**Issue by darkeoftime** [asoji/hackintosh-rog-strix-b550f#2]
Hi, How are you ?
i found your EFI that for my config, I want use it but the only things that bothers me is for my GPU, I need a answer please… Does the efi works with the MSI Radeon RX 570 Armor 8GB OC ? PLEASE (I ask you that cause I had an old GPU and I’m starting to hate windows (even if they had good things) and I want it to change to Mac OS with an hackintosh but I need a new GPU ´cause is to old and I only find MSI Radeon RX 570 Armor 8GB OC so that’s why I ask if it’s work with this one too.)

thanks in advance for your answers and have a good week.

**Comment by asoji** [comment]
It should work, that's the GPU I have, but you can feel free to try before you wipe Windows.
